CREATE TABLE books (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE user_books (
    userid integer NOT NULL,
    bookid integer NOT NULL
);


CREATE TABLE users (
    id integer NOT NULL ADD GENERATED BY DEFAULT AS IDENTITY,
    name character varying(64) NOT NULL,
    surname character varying(64) NOT NULL,
    email character varying(255) NOT NULL,
    created timestamp without time zone DEFAULT now()
);
